// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService.Persistences;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationService.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    partial class NotificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationService.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("72222222-2222-4222-8222-222222222222"),
                            Body = "Your account is ready to receive order updates.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            ReferenceType = "user",
                            Title = "Welcome to Food Delivery",
                            Type = "system",
                            UserId = new Guid("aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("74444444-4444-4444-8444-444444444444"),
                            Body = "The merchant has confirmed the order and it is being prepared for delivery.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 10, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            ReferenceId = new Guid("62222222-2222-4222-8222-222222222222"),
                            ReferenceType = "delivery_tracking",
                            Title = "Your order is being prepared",
                            Type = "order_update",
                            UserId = new Guid("aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("75555555-5555-4555-8555-555555555555"),
                            Body = "You have a new order waiting for pickup.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 15, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            ReferenceId = new Guid("64444444-4444-4444-8444-444444444444"),
                            ReferenceType = "delivery_assignment",
                            Title = "New delivery assignment",
                            Type = "assignment",
                            UserId = new Guid("99999999-9999-4999-9999-999999999999")
                        });
                });

            modelBuilder.Entity("NotificationService.Entities.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("UserDevices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("73333333-3333-4333-8333-333333333333"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviceToken = "seed-device-token",
                            DeviceType = "Android",
                            IsActive = true,
                            UserId = new Guid("aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("76666666-6666-4666-8666-666666666666"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviceToken = "seed-merchant-device-token",
                            DeviceType = "Web",
                            IsActive = true,
                            UserId = new Guid("bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-4777-8777-777777777777"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviceToken = "seed-shipper-device-token",
                            DeviceType = "Ios",
                            IsActive = true,
                            UserId = new Guid("99999999-9999-4999-9999-999999999999")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
