services:
  report-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: report-service
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      PORT: ${REPORT_SERVICE_CONTAINER_PORT:-8080}
    ports:
      - "${REPORT_SERVICE_HOST_PORT:-8088}:${REPORT_SERVICE_CONTAINER_PORT:-8080}"
    depends_on:
      report-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - backend-network

  report-db:
    image: postgres:17-alpine
    container_name: report-db
    restart: unless-stopped
    env_file:
      - ../../Infrastructure/report-db.env
    ports:
      - "${REPORT_DB_PORT:-5437}:5432"
    volumes:
      - report_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  report_db_data:
