services:
  apigateway:
    extends:
      file: ./Services/ApiGateway/docker-compose.yml
      service: apigateway

  authentication-service:
    extends:
      file: ./Services/AuthenticationService/docker-compose.yml
      service: authentication-service

  authentication-db:
    extends:
      file: ./Services/AuthenticationService/docker-compose.yml
      service: authentication-db

  user-service:
    extends:
      file: ./Services/UserService/docker-compose.yml
      service: user-service

  user-db:
    extends:
      file: ./Services/UserService/docker-compose.yml
      service: user-db

  address-service:
    extends:
      file: ./Services/AddressService/docker-compose.yml
      service: address-service

  address-db:
    extends:
      file: ./Services/AddressService/docker-compose.yml
      service: address-db

  file-service:
    extends:
      file: ./Services/FileService/docker-compose.yml
      service: file-service

  notification-service:
    extends:
      file: ./Services/NotificationService/docker-compose.yml
      service: notification-service

  notification-db:
    extends:
      file: ./Services/NotificationService/docker-compose.yml
      service: notification-db

  delivery-service:
    extends:
      file: ./Services/DeliveryService/docker-compose.yml
      service: delivery-service

  delivery-db:
    extends:
      file: ./Services/DeliveryService/docker-compose.yml
      service: delivery-db

  delivery-redis:
    extends:
      file: ./Services/DeliveryService/docker-compose.yml
      service: delivery-redis

  catalog-service:
    extends:
      file: ./Services/CatalogService/docker-compose.yml
      service: catalog-service

  order-service:
    extends:
      file: ./Services/OrderService/docker-compose.yml
      service: order-service

  report-service:
    extends:
      file: ./Services/ReportService/docker-compose.yml
      service: report-service

  wallet-service:
    extends:
      file: ./Services/WalletService/docker-compose.yml
      service: wallet-service

  order-db:
    extends:
      file: ./Services/OrderService/docker-compose.yml
      service: order-db

  report-db:
    extends:
      file: ./Services/ReportService/docker-compose.yml
      service: report-db

  order-redis:
    extends:
      file: ./Services/OrderService/docker-compose.yml
      service: order-redis

  wallet-db:
    extends:
      file: ./Services/WalletService/docker-compose.yml
      service: wallet-db

  rabbitmq:
    extends:
      file: ./Infrastructure/docker-compose.yml
      service: rabbitmq

networks:
  backend-network:
    driver: bridge

volumes:
  authentication_db_data:
  user_db_data:
  address_db_data:
  delivery_db_data:
  order_db_data:
  order_redis_data:
  notification_db_data:
  report_db_data:
  wallet_db_data:
  rabbitmq_data:
