// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.Persistences;

#nullable disable

namespace UserService.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20260524141118_MakeRequestReviewerOptional")]
    partial class MakeRequestReviewerOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Lng")
                        .HasColumnType("numeric");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-4ddd-8ddd-dddddddddddd"),
                            AddressLine = "1 Nguyen Hue",
                            City = "Ho Chi Minh City",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "District 1",
                            IsDefault = true,
                            Label = "Home",
                            Lat = 10.7769m,
                            Lng = 106.7009m,
                            Phone = "0900000001",
                            RecipientName = "Seeded Customer",
                            UserId = new Guid("aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa"),
                            Ward = "Ben Nghe"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee"),
                            AddressLine = "2 Le Loi",
                            City = "Ho Chi Minh City",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "District 1",
                            IsDefault = true,
                            Label = "Store Contact",
                            Lat = 10.7722m,
                            Lng = 106.6983m,
                            Phone = "0900000002",
                            RecipientName = "Seeded Merchant Owner",
                            UserId = new Guid("bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb"),
                            Ward = "Ben Thanh"
                        },
                        new
                        {
                            Id = new Guid("12121212-1212-4212-8212-121212121212"),
                            AddressLine = "3 Nguyen Trai",
                            City = "Ho Chi Minh City",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "District 1",
                            IsDefault = true,
                            Label = "Home",
                            Lat = 10.7691m,
                            Lng = 106.6824m,
                            Phone = "0900000003",
                            RecipientName = "Seeded Shipper",
                            UserId = new Guid("99999999-9999-4999-9999-999999999999"),
                            Ward = "Pham Ngu Lao"
                        });
                });

            modelBuilder.Entity("UserService.Entities.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AvgPrepTime")
                        .HasColumnType("integer");

                    b.Property<string>("BusinessLicense")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("ClosingTime")
                        .HasColumnType("interval");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasColumnType("numeric");

                    b.Property<TimeSpan?>("OpeningTime")
                        .HasColumnType("interval");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StoreBannerUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoreDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoreLogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Merchants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-4ccc-8ccc-cccccccccccc"),
                            AvgPrepTime = 20,
                            BusinessLicense = "BL-SEED-0001",
                            ClosingTime = new TimeSpan(0, 22, 0, 0, 0),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOpen = true,
                            MinOrderAmount = 30000m,
                            OpeningTime = new TimeSpan(0, 8, 0, 0, 0),
                            Status = 1,
                            StoreBannerUrl = "https://example.com/stores/banner.png",
                            StoreDescription = "Default merchant store for local development.",
                            StoreLogoUrl = "https://example.com/stores/logo.png",
                            StoreName = "Seeded Merchant Store",
                            TaxId = "TAX-SEED-0001",
                            UserId = new Guid("bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb")
                        });
                });

            modelBuilder.Entity("UserService.Entities.MerchantAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Lng")
                        .HasColumnType("numeric");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.ToTable("MerchantAddresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-4fff-8fff-ffffffffffff"),
                            AddressLine = "2 Le Loi",
                            City = "Ho Chi Minh City",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "District 1",
                            Lat = 10.7722m,
                            Lng = 106.6983m,
                            MerchantId = new Guid("cccccccc-cccc-4ccc-8ccc-cccccccccccc"),
                            Ward = "Ben Thanh"
                        });
                });

            modelBuilder.Entity("UserService.Entities.MerchantRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessLicense")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessLicenseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectedReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("StoreDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("UserId");

                    b.ToTable("MerchantRequests");
                });

            modelBuilder.Entity("UserService.Entities.Shipper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VehiclePlate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Shippers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("56565656-5656-4656-8656-565656565656"),
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequestId = new Guid("34343434-3434-4434-8434-343434343434"),
                            Status = 1,
                            UserId = new Guid("99999999-9999-4999-9999-999999999999"),
                            VehiclePlate = "59A-123.45"
                        });
                });

            modelBuilder.Entity("UserService.Entities.ShipperRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdCardBackUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdCardFrontUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LicenseBackUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LicenseFrontUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RejectedReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("SelfieUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("UserId");

                    b.ToTable("ShipperRequest");

                    b.HasData(
                        new
                        {
                            Id = new Guid("34343434-3434-4434-8434-343434343434"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1998, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Seeded Shipper",
                            IdCardBackUrl = "https://example.com/shipper/id-back.jpg",
                            IdCardFrontUrl = "https://example.com/shipper/id-front.jpg",
                            IdNumber = "079202600001",
                            LicenseBackUrl = "https://example.com/shipper/license-back.jpg",
                            LicenseFrontUrl = "https://example.com/shipper/license-front.jpg",
                            LicenseNumber = "DL-SEED-0001",
                            RejectedReason = "",
                            ReviewedBy = new Guid("bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb"),
                            SelfieUrl = "https://example.com/shipper/selfie.jpg",
                            UserId = new Guid("99999999-9999-4999-9999-999999999999"),
                            VerificationStatus = 1,
                            VerifiedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("UserService.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ShipperId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa"),
                            AvatarUrl = "https://example.com/avatars/customer.png",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Seeded Customer",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb"),
                            AvatarUrl = "https://example.com/avatars/merchant.png",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Seeded Merchant Owner",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-4999-9999-999999999999"),
                            AvatarUrl = "https://example.com/avatars/shipper.png",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Seeded Shipper",
                            Status = 0
                        });
                });

            modelBuilder.Entity("UserService.Entities.Address", b =>
                {
                    b.HasOne("UserService.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.Entities.Merchant", b =>
                {
                    b.HasOne("UserService.Entities.User", "User")
                        .WithOne("Merchant")
                        .HasForeignKey("UserService.Entities.Merchant", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.Entities.MerchantAddress", b =>
                {
                    b.HasOne("UserService.Entities.Merchant", "Merchant")
                        .WithMany("Addresses")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("UserService.Entities.MerchantRequest", b =>
                {
                    b.HasOne("UserService.Entities.User", "ReviewedUser")
                        .WithMany()
                        .HasForeignKey("ReviewedBy");

                    b.HasOne("UserService.Entities.User", "User")
                        .WithMany("MerchantRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.Entities.Shipper", b =>
                {
                    b.HasOne("UserService.Entities.ShipperRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.Entities.User", "User")
                        .WithOne("Shipper")
                        .HasForeignKey("UserService.Entities.Shipper", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.Entities.ShipperRequest", b =>
                {
                    b.HasOne("UserService.Entities.User", "ReviewedUser")
                        .WithMany()
                        .HasForeignKey("ReviewedBy");

                    b.HasOne("UserService.Entities.User", "User")
                        .WithMany("ShipperRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.Entities.Merchant", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("UserService.Entities.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Merchant");

                    b.Navigation("MerchantRequests");

                    b.Navigation("Shipper");

                    b.Navigation("ShipperRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
