// <auto-generated />
using System;
using DeliveryService.Persistences;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeliveryService.Migrations
{
    [DbContext(typeof(DeliveryDbContext))]
    partial class DeliveryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeliveryService.Entities.DeliveryFeeDistanceTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("FeePerKm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("FromKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ToKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.ToTable("DeliveryFeeDistanceTiers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("82222222-2222-4222-8222-222222222222"),
                            FeePerKm = 0m,
                            FromKm = 0m,
                            PolicyId = new Guid("81111111-1111-4111-8111-111111111111"),
                            ToKm = 2m
                        },
                        new
                        {
                            Id = new Guid("83333333-3333-4333-8333-333333333333"),
                            FeePerKm = 4000m,
                            FromKm = 2m,
                            PolicyId = new Guid("81111111-1111-4111-8111-111111111111"),
                            ToKm = 5m
                        },
                        new
                        {
                            Id = new Guid("84444444-4444-4444-8444-444444444444"),
                            FeePerKm = 5000m,
                            FromKm = 5m,
                            PolicyId = new Guid("81111111-1111-4111-8111-111111111111"),
                            ToKm = 10m
                        },
                        new
                        {
                            Id = new Guid("85555555-5555-4555-8555-555555555555"),
                            FeePerKm = 6000m,
                            FromKm = 10m,
                            PolicyId = new Guid("81111111-1111-4111-8111-111111111111")
                        });
                });

            modelBuilder.Entity("DeliveryService.Entities.DeliveryFeePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("MinFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("RushHourSurcharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SmallOrderSurcharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("SmallOrderThreshold")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("DeliveryFeePolicies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("81111111-1111-4111-8111-111111111111"),
                            BaseFee = 10000m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxFee = 60000m,
                            MinFee = 10000m,
                            Name = "Default Delivery Fee Policy",
                            RushHourSurcharge = 5000m,
                            SmallOrderSurcharge = 5000m,
                            SmallOrderThreshold = 50000m
                        });
                });

            modelBuilder.Entity("DeliveryService.Entities.DeliveryFeeQuote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("DeliveryFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("DistanceKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("DropoffLat")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<decimal>("DropoffLng")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<bool>("IsRushHour")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PickupLat")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<decimal>("PickupLng")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("DeliveryFeeQuotes");
                });

            modelBuilder.Entity("DeliveryService.Entities.DeliveryFeeQuoteDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DistanceFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("FinalFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsRushHour")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSmallOrder")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RawFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("RushHourSurcharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SmallOrderSurcharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.HasIndex("QuoteId");

                    b.ToTable("DeliveryFeeQuoteDetails");
                });

            modelBuilder.Entity("DeliveryService.Entities.DeliveryTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ActualTime")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DeliveryLat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DeliveryLng")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("numeric");

                    b.Property<int>("EstimatedTime")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PickupLat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PickupLng")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ShipperId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DeliveryTrackings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("61111111-1111-4111-8111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeliveryLat = 10.7700m,
                            DeliveryLng = 106.6950m,
                            DistanceKm = 2.2m,
                            EstimatedTime = 15,
                            OrderId = new Guid("62222222-2222-4222-8222-222222222222"),
                            PickupLat = 10.7769m,
                            PickupLng = 106.7009m,
                            ShipperId = new Guid("56565656-5656-4656-8656-565656565656"),
                            Status = "Assigned"
                        },
                        new
                        {
                            Id = new Guid("74444444-4444-4444-8444-444444444444"),
                            ActualTime = 14,
                            CreatedAt = new DateTime(2025, 12, 31, 23, 0, 0, 0, DateTimeKind.Utc),
                            DeliveryLat = 10.7770m,
                            DeliveryLng = 106.7002m,
                            DistanceKm = 1.8m,
                            EstimatedTime = 12,
                            OrderId = new Guid("75555555-5555-4555-8555-555555555555"),
                            PickupLat = 10.7821m,
                            PickupLng = 106.6925m,
                            ShipperId = new Guid("56565656-5656-4656-8656-565656565656"),
                            Status = "Delivered"
                        });
                });

            modelBuilder.Entity("DeliveryService.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("ProofUrl")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("ReportedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Incidents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-4777-8777-777777777777"),
                            CreatedAt = new DateTime(2025, 12, 31, 23, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Customer reported one missing item from the delivered order.",
                            OrderId = new Guid("75555555-5555-4555-8555-555555555555"),
                            ProofUrl = new[] { "https://example.com/incidents/order-2-photo-1.jpg", "https://example.com/incidents/order-2-photo-2.jpg" },
                            ReportedBy = new Guid("aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa"),
                            Resolution = "Awaiting support review and customer confirmation.",
                            Status = "Investigating",
                            Type = "MissingItem"
                        });
                });

            modelBuilder.Entity("DeliveryService.Entities.ShipperAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CancelledReason")
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("numeric");

                    b.Property<string>("DeliveryProofFileKey")
                        .HasColumnType("text");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("numeric");

                    b.Property<string>("DropoffAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DropoffLatitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DropoffLongitude")
                        .HasColumnType("numeric");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("OfferExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PickupLatitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PickupLongitude")
                        .HasColumnType("numeric");

                    b.Property<string>("PickupProofFileKey")
                        .HasColumnType("text");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShipperId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Accepted'");

                    b.HasIndex("Status");

                    b.HasIndex("OrderId", "ShipperId")
                        .IsUnique();

                    b.ToTable("ShipperAssignments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("64444444-4444-4444-8444-444444444444"),
                            AcceptedAt = new DateTime(2026, 1, 1, 0, 1, 0, 0, DateTimeKind.Utc),
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa"),
                            DeliveryFee = 21000m,
                            DistanceKm = 2.2m,
                            DropoffAddress = "Seed dropoff address",
                            DropoffLatitude = 10.7700m,
                            DropoffLongitude = 106.6950m,
                            MerchantId = new Guid("bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb"),
                            MerchantName = "Seed Merchant",
                            OrderId = new Guid("62222222-2222-4222-8222-222222222222"),
                            OrderNumber = "ORD-SEED-0001",
                            PickupAddress = "Seed pickup address",
                            PickupLatitude = 10.7769m,
                            PickupLongitude = 106.7009m,
                            ShipperId = new Guid("56565656-5656-4656-8656-565656565656"),
                            Status = "Accepted"
                        });
                });

            modelBuilder.Entity("DeliveryService.Entities.ShipperAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CurrentLat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CurrentLng")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("CurrentOfferedAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentOrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OfferingExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShipperId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurrentAssignmentId");

                    b.HasIndex("CurrentOfferedAssignmentId");

                    b.HasIndex("Status");

                    b.ToTable("ShipperAvailabilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-4666-8666-666666666666"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentLat = 10.7735m,
                            CurrentLng = 106.6975m,
                            CurrentOrderId = new Guid("62222222-2222-4222-8222-222222222222"),
                            LastSeenAt = new DateTime(2026, 1, 1, 0, 5, 0, 0, DateTimeKind.Utc),
                            ShipperId = new Guid("56565656-5656-4656-8656-565656565656"),
                            Status = "Delivering"
                        });
                });

            modelBuilder.Entity("DeliveryService.Entities.ShipperLocationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShipperId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "RecordedAt");

                    b.HasIndex("ShipperId", "RecordedAt");

                    b.ToTable("ShipperLocationHistories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("65555555-5555-4555-8555-555555555555"),
                            CorrelationId = "seed-delivery",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 10.7735m,
                            Longitude = 106.6975m,
                            OrderId = new Guid("62222222-2222-4222-8222-222222222222"),
                            RecordedAt = new DateTime(2026, 1, 1, 0, 5, 0, 0, DateTimeKind.Utc),
                            ShipperId = new Guid("56565656-5656-4656-8656-565656565656")
                        },
                        new
                        {
                            Id = new Guid("76666666-6666-4666-8666-666666666666"),
                            CorrelationId = "seed-delivery-completed",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 10.7785m,
                            Longitude = 106.6990m,
                            OrderId = new Guid("75555555-5555-4555-8555-555555555555"),
                            RecordedAt = new DateTime(2026, 1, 1, 0, 25, 0, 0, DateTimeKind.Utc),
                            ShipperId = new Guid("56565656-5656-4656-8656-565656565656")
                        });
                });

            modelBuilder.Entity("DeliveryService.Entities.DeliveryFeeDistanceTier", b =>
                {
                    b.HasOne("DeliveryService.Entities.DeliveryFeePolicy", "Policy")
                        .WithMany("DistanceTiers")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("DeliveryService.Entities.DeliveryFeeQuoteDetail", b =>
                {
                    b.HasOne("DeliveryService.Entities.DeliveryFeePolicy", "Policy")
                        .WithMany("QuoteDetails")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliveryService.Entities.DeliveryFeeQuote", "Quote")
                        .WithMany("Details")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("DeliveryService.Entities.DeliveryFeePolicy", b =>
                {
                    b.Navigation("DistanceTiers");

                    b.Navigation("QuoteDetails");
                });

            modelBuilder.Entity("DeliveryService.Entities.DeliveryFeeQuote", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
