// <auto-generated />
using System;
using DeliveryService.Persistences;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeliveryService.Migrations
{
    [DbContext(typeof(DeliveryDbContext))]
    partial class DeliveryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeliveryService.Entities.DeliveryTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ActualTime")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DeliveryLat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DeliveryLng")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("numeric");

                    b.Property<int>("EstimatedTime")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PickupLat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PickupLng")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ShipperId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DeliveryTrackings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("61111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeliveryLat = 10.7700m,
                            DeliveryLng = 106.6950m,
                            DistanceKm = 2.2m,
                            EstimatedTime = 15,
                            OrderId = new Guid("62222222-2222-2222-2222-222222222222"),
                            PickupLat = 10.7769m,
                            PickupLng = 106.7009m,
                            ShipperId = new Guid("56565656-5656-5656-5656-565656565656"),
                            Status = "Assigned"
                        },
                        new
                        {
                            Id = new Guid("74444444-4444-4444-4444-444444444444"),
                            ActualTime = 14,
                            CreatedAt = new DateTime(2025, 12, 31, 23, 0, 0, 0, DateTimeKind.Utc),
                            DeliveryLat = 10.7770m,
                            DeliveryLng = 106.7002m,
                            DistanceKm = 1.8m,
                            EstimatedTime = 12,
                            OrderId = new Guid("75555555-5555-5555-5555-555555555555"),
                            PickupLat = 10.7821m,
                            PickupLng = 106.6925m,
                            ShipperId = new Guid("56565656-5656-5656-5656-565656565656"),
                            Status = "Delivered"
                        });
                });

            modelBuilder.Entity("DeliveryService.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("ProofUrl")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("ReportedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Incidents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2025, 12, 31, 23, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Customer reported one missing item from the delivered order.",
                            OrderId = new Guid("75555555-5555-5555-5555-555555555555"),
                            ProofUrl = new[] { "https://example.com/incidents/order-2-photo-1.jpg", "https://example.com/incidents/order-2-photo-2.jpg" },
                            ReportedBy = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Resolution = "Awaiting support review and customer confirmation.",
                            Status = "Investigating",
                            Type = "MissingItem"
                        });
                });

            modelBuilder.Entity("DeliveryService.Entities.ShipperAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("numeric");

                    b.Property<string>("DeliveryProofFileKey")
                        .HasColumnType("text");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("numeric");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PickupProofFileKey")
                        .HasColumnType("text");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShipperId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ShipperAssignments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("64444444-4444-4444-4444-444444444444"),
                            AcceptedAt = new DateTime(2026, 1, 1, 0, 1, 0, 0, DateTimeKind.Utc),
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            DeliveryFee = 21000m,
                            DistanceKm = 2.2m,
                            MerchantId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            OrderId = new Guid("62222222-2222-2222-2222-222222222222"),
                            OrderNumber = "ORD-SEED-0001",
                            ShipperId = new Guid("56565656-5656-5656-5656-565656565656"),
                            Status = "Accepted"
                        });
                });

            modelBuilder.Entity("DeliveryService.Entities.ShipperAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentLat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CurrentLng")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("CurrentOrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShipperId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ShipperAvailabilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentLat = 10.7735m,
                            CurrentLng = 106.6975m,
                            CurrentOrderId = new Guid("62222222-2222-2222-2222-222222222222"),
                            LastSeenAt = new DateTime(2026, 1, 1, 0, 5, 0, 0, DateTimeKind.Utc),
                            ShipperId = new Guid("56565656-5656-5656-5656-565656565656"),
                            Status = "Delivering"
                        });
                });

            modelBuilder.Entity("DeliveryService.Entities.ShipperLocationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShipperId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "RecordedAt");

                    b.HasIndex("ShipperId", "RecordedAt");

                    b.ToTable("ShipperLocationHistories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("65555555-5555-5555-5555-555555555555"),
                            CorrelationId = "seed-delivery",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 10.7735m,
                            Longitude = 106.6975m,
                            OrderId = new Guid("62222222-2222-2222-2222-222222222222"),
                            RecordedAt = new DateTime(2026, 1, 1, 0, 5, 0, 0, DateTimeKind.Utc),
                            ShipperId = new Guid("56565656-5656-5656-5656-565656565656")
                        },
                        new
                        {
                            Id = new Guid("76666666-6666-6666-6666-666666666666"),
                            CorrelationId = "seed-delivery-completed",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 10.7785m,
                            Longitude = 106.6990m,
                            OrderId = new Guid("75555555-5555-5555-5555-555555555555"),
                            RecordedAt = new DateTime(2026, 1, 1, 0, 25, 0, 0, DateTimeKind.Utc),
                            ShipperId = new Guid("56565656-5656-5656-5656-565656565656")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
